# mssql need strong password to startup
version: '3'

services:
    db:
        image: mcr.microsoft.com/mssql/server
        ports: 
            - "127.0.0.1:1433:1433"
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: YourStrong!Passw0rd233
