version: '3'
services:
  proxy_pool:
    image: jhao104/proxy_pool
    ports:
      - "5010:5010"
    links:
      - proxy_redis
    environment:
      db_type: REDIS
      db_host: proxy_redis
      db_port: 6379
  proxy_redis:
    image: "redis"
