version: '3'

services:
    nfs:
        image: itsthenetwork/nfs-server-alpine
        volumes:
            - ./tmp:/nfsshare
        privileged: true
        environment:
            SHARED_DIRECTORY: /nfsshare
        ports: 
            - "111:111"
            - "2049:2049"
