version: '3'

services:
  editor:
    image: swaggerapi/swagger-editor
    ports:
      - "8081:8080"
  ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8082:8080"
    volumes:
      - ./swagger/openapi.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json
