DROP DATABASE IF EXISTS `cve`;

CREATE DATABASE `cve` DEFAULT CHARACTER SET utf8mb4 collate utf8mb4_general_ci;

use `cve`;

CREATE TABLE `cve` (
  `number` VARCHAR(32) PRIMARY KEY NOT NULL,
  `name` VARCHAR(2048) NOT NULL DEFAULT "",
  `version` VARCHAR(2048) NOT NULL DEFAULT "",
  `desc` VARCHAR(4096) NOT NULL  DEFAULT ""
);
