version: '3'

services:
    nfs:
        image: erichough/nfs-server
        privileged: true
        volumes:
            - ./exports:/etc/exports:ro
            - ./tmp:/nfsshare
        network_mode: host
        cap_add:
            - SYS_ADMIN
        environment:
            NFS_LOG_LEVEL: DEBUG
